# Generated by Django 2.1.7 on 2019-03-31 20:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownsegment',
            name='content',
            field=models.TextField(default=1, max_length=8000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markdownsegment',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='markdownsegment',
            name='order',
            field=models.IntegerField(db_index=True, help_text='Int asc. order', unique=True),
        ),
    ]
