# Generated by Django 2.1.7 on 2019-04-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markdownsegment',
            old_name='markdown_page',
            new_name='topic',
        ),
    ]
