# Generated by Django 2.1.7 on 2019-04-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20190405_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
