# Generated by Django 2.1.7 on 2019-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_topic_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False, help_text='All content from existing md file'),
        ),
    ]
