# Generated by Django 2.1.7 on 2019-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20190409_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
